# Generated by Django 4.0.3 on 2022-06-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_print_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='print',
            options={'verbose_name': 'Печать', 'verbose_name_plural': 'Печати'},
        ),
    ]
