# Generated by Django 4.0.3 on 2022-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='appointment_procedures',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='procedures_perform',
            field=models.IntegerField(),
        ),
    ]
