# Generated by Django 4.0.3 on 2022-05-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_print_treatment'),
        ('treatment', '0002_alter_treatment_appointment_procedures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='print',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='analysis.print'),
            preserve_default=False,
        ),
    ]
