# Generated by Django 4.0.3 on 2022-06-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_alter_treatment_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='value',
            field=models.CharField(max_length=1000),
        ),
    ]
