# Generated by Django 4.0.3 on 2022-06-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_assigntreat'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='assign_treat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.assigntreat'),
        ),
    ]
