# Generated by Django 4.0.3 on 2022-06-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_options_alter_patient_analysis_options'),
        ('treatment', '0007_alter_assigntreat_options_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='appointment_procedures',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient_analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient_analysis'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='procedures_perform',
            field=models.IntegerField(null=True),
        ),
    ]
