# Generated by Django 4.0.3 on 2022-05-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='number_of_deliveries',
        ),
        migrations.CreateModel(
            name='Drug_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.drug')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='drugs',
            field=models.ManyToManyField(to='materials.drug_order'),
        ),
    ]
