# Generated by Django 4.0.3 on 2022-06-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_drug_options_alter_drug_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='drugs',
        ),
        migrations.AddField(
            model_name='place',
            name='drugs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materials.drug_order', verbose_name='Назви препаратів'),
            preserve_default=False,
        ),
    ]
