# Generated by Django 4.0.3 on 2022-05-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complains', models.CharField(max_length=100)),
                ('survey_type', models.CharField(max_length=100)),
                ('scheduled', models.CharField(max_length=100)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.CharField(max_length=100)),
                ('includes', models.CharField(max_length=100)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.reception')),
            ],
        ),
    ]
