# Generated by Django 4.0.3 on 2022-06-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'verbose_name': 'Рецепт повний', 'verbose_name_plural': 'Рецепти повні'},
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепти'},
        ),
    ]
