# Generated by Django 4.0.3 on 2022-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_inspection_options_alter_reception_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Вид обстеження\t',
                'verbose_name_plural': 'Вид обстеження\t',
            },
        ),
    ]
