# Generated by Django 4.0.3 on 2022-06-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='survey_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.survey'),
        ),
    ]
