# Generated by Django 4.0.3 on 2022-06-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0007_alter_assigntreat_options_alter_diagnosis_options_and_more'),
        ('appointment', '0004_alter_reception_survey_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='includes',
            field=models.CharField(max_length=100, verbose_name='Включения'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.reception', verbose_name='Прийом'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='survey',
            field=models.CharField(max_length=100, verbose_name='Обследование'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='complains',
            field=models.CharField(max_length=100, verbose_name='Жалоби'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='scheduled',
            field=models.CharField(max_length=100, verbose_name='Назва ліків'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='survey_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.survey', verbose_name='Тип опроса'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment', verbose_name='Назва ліків'),
        ),
    ]
