# Generated by Django 4.0.3 on 2022-06-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_inspection_date_of_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='time_of_receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
